// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Mycrowd.Task.Model;

namespace Mycrowd.Task.Model
{

    public class Task
    {

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("job_type")]
        public string JobType { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("terms_attributes")]
        public TermsAttributes TermsAttributes { get; set; }

        [JsonProperty("visibility")]
        public string Visibility { get; set; }

        [JsonProperty("team_id")]
        public object TeamId { get; set; }

        [JsonProperty("asset_collection_attributes")]
        public AssetCollectionAttributes AssetCollectionAttributes { get; set; }
    }

}
