// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Assets
{

    public class Assets
    {

        [JsonProperty("assets_List")]
        public AssetsList[] AssetsList { get; set; }
    }

}
