// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Mycrowd.Task.Model;

namespace Mycrowd.Task.Model
{

    public class AssetCollectionAttributes
    {

        [JsonProperty("assets_attributes")]
        public AssetsAttribute[] AssetsAttributes { get; set; }
    }

}
