// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Assets
{

    public class AssetFile
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("asset_id")]
        public int AssetId { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("created_at")]
        public string CreatedAt { get; set; }

        [JsonProperty("lookup_key")]
        public string LookupKey { get; set; }

        [JsonProperty("key_file_name")]
        public object KeyFileName { get; set; }

        [JsonProperty("key_file_size")]
        public object KeyFileSize { get; set; }

        [JsonProperty("content_type")]
        public string ContentType { get; set; }

        [JsonProperty("height")]
        public int Height { get; set; }

        [JsonProperty("width")]
        public int Width { get; set; }

        [JsonProperty("final")]
        public bool Final { get; set; }
    }

}
