// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Mycrowd.Task.Model;

namespace Mycrowd.Task.Model
{

    public class TermsAttributes
    {

        [JsonProperty("payment_type")]
        public string PaymentType { get; set; }

        [JsonProperty("budget")]
        public string Budget { get; set; }

        [JsonProperty("duration")]
        public string Duration { get; set; }
    }

}
